### ISSUE TITLE
tvi24

### ISSUE THREAD

**Issue by daniel3xxx** [brunomiguel/antinonio#11]
Boas
o script não funciona no site https://tvi24.iol.pt/
exemplo: https://tvi24.iol.pt/direto/1203/tvi24-a-atualidade-em-direto

Obrigado

**Comment by brunomiguel** [comment]
Adicionei duas regras específicas para o site. Podes atualizar os filtros do adblocker e confirmar se está resolvido?

**Comment by daniel3xxx** [comment]
Resolvido.

Obrigado e bom trabalho
