### ISSUE TITLE
Lista de sites a testar

### ISSUE THREAD

**Issue by PJFonseca** [brunomiguel/antinonio#13]
@brunomiguel , 

Tens como ToDo: testar lista em 50% dos sites da rede nonio

Tens alguma lista? Se existir essa lista, podiamos ir partilhando o esforço.

**Comment by Perksls** [comment]
[aqui](https://nonio.pt/) no fundo tens os sites.

já dei uma vista de olhos há dias e pareceu-me que está tudo bem

**Comment by PJFonseca** [comment]
OK, vou só re-verificar e se encontrar alguma coisa, eu apito.

**Comment by brunomiguel** [comment]
Para a semana já devo fazer uma listagem, para garantir que testo com todos os sites do nonio. Se depois quiseres ajudar, agradeço! :)

**Comment by PJFonseca** [comment]
Vamos a isso.

**Comment by Perksls** [comment]
Estive a passar os olhos hoje, encontrei as do grupo Renascença, daí o PR

grupo Impresa e Cofina não tive nenhum pop-up

**Comment by brunomiguel** [comment]
Era para ter feito uma listagem dos sites a testar, mas uma virose que apanhei no fim-de-semana obrigou-me a rever a data para isto. Assim que estiver melhor (tenho ido trabalhar assim, por isso quando chego a casa já só quero cama), meto as mãos na massa. Claro que se alguém quiser antecipar, está à vontade :+1:

**Comment by Perksls** [comment]
tomei a liberdade (bendito feriado) de meter num [sheet do docs](https://docs.google.com/spreadsheets/d/1vxu_4ByAmjx1qbHv7H41vd8lRRw3-JbJWdF80ITsTs4/edit#gid=0). 
tem os sites e os endereços, basta entrar e marcar a caixa de "teste OK" 
fica marcado e com a data que se testou, se entretanto algum site voltar a aparecer o pop-up e se estiver lá marcado sabemos que foi algo alterado do "lado de lá"

Fica a sugestão...

**Comment by PJFonseca** [comment]
Tudo o que está no sapo.pt aparece assim.
![Screenshot-20190610200843-915x895](https://user-images.githubusercontent.com/3879175/59220163-302ed980-8bbc-11e9-8af1-e9ff67efce56.png)

É normal? Ou é o meu fedora que está a bloquear demais? :)

**Comment by Perksls** [comment]
Aqui abre ok @PJFonseca 

há dias a Mozilla começou a bloquear tracking cookies e scripts, não será disso?

**Comment by PJFonseca** [comment]
Testei quase tudo. Adicionei mais umas regras e apenas deixar por testar os do Sapo. Deve ter a ver com o meu [método de ublock](https://github.com/PJFonseca/dotfiles/blob/master/system/.housekeeping#L10)

**Comment by brunomiguel** [comment]
> Tudo o que está no sapo.pt aparece assim.
> ![Screenshot-20190610200843-915x895](https://user-images.githubusercontent.com/3879175/59220163-302ed980-8bbc-11e9-8af1-e9ff67efce56.png)
> 
> É normal? Ou é o meu fedora que está a bloquear demais? :)

Eu consigo abrir bem, com as regras acabadas de atualizar. Talvez algum stress com a cache do browser?

**Comment by Perksls** [comment]
Inseri mais uns sites, e testei. 

Diria que isto está, não?

**Comment by PJFonseca** [comment]
Eu diria que sim.

**Comment by brunomiguel** [comment]
Fechado :)
