### ISSUE TITLE
brpx.com e brpx.io

### ISSUE THREAD

**Issue by cdeath** [brunomiguel/antinonio#14]
estavam a correr coisas experimentais e temporárias no site do público. já não há nada a correr. podem verificar e elimina-los da lista?

**Comment by PJFonseca** [comment]
Acabei de verificar. Se desactivar o uBlock com as regras do antinonio, levo logo com o NONIO!
Portanto, o que pretendes que seja feito mesmo? Não estou a entender.

**Comment by cdeath** [comment]
basicamente tens esses dois domínios na lista de bloqueio, sem motivo nenhum.

abri um PR. obrigado.

**Comment by brunomiguel** [comment]
Aceitei o PR. Se, no entanto, no futuro se confirmar que é necessário adicionar os domínios à lista, serão adicionados. Eles, como referi no PR, vêm de uma lista que tinha sido feita para o uMatrix
