### ISSUE TITLE
Falha em utilizar a lista

### ISSUE THREAD

**Issue by leplastic** [brunomiguel/antinonio#18]
Tive contacto com o projeto Anti-Nónio no Reddit e desde então tenho começado a usar no Firefox. O problema foi que hoje reparei que a lista não é válida, pelo menos no ABP:

![imagem](https://user-images.githubusercontent.com/1301770/65393681-c2c64380-dd7b-11e9-89e6-eb4685db079b.png)

No entanto, se usar a lista que está neste repo já funciona corretamente. Posso continuar a usar esta lista para resolver o problema (é o que vou fazer já que está mais completa), mas a lista do site principal poderia estar pelo menos funcional para quem quer evitar o tracking da plataforma.

Firefox: 69.0.1
ABP: 3.6.3

**Comment by brunomiguel** [comment]
Acabei de testar e funciona. Certifica-te que usas esta link: https://raw.githubusercontent.com/brunomiguel/antinonio/master/antinonio.txt
Vou fechar o bug-report porque funcionou comigo com o mesmo setup. Se continuares a ter problemas, reabre-o, por favor.

**Comment by leplastic** [comment]
Peço desculpa por não ter sido claro. Eu referia-me ao do site do nonio.pt

https://nonio.pt/antinonio.txt

A lista deste repo, tal como dizes, funciona perfeitamente e é a que estou a usar agora em substituição.

**Comment by brunomiguel** [comment]
Recomendo-te que reportes o bug em https://github.com/tomahock/anti-nonio. Na prática, falta só adicionar [Adblock Plus 2.0] ao ficheiro
