### ISSUE TITLE
Sic

### ISSUE THREAD

**Issue by daniel3xxx** [brunomiguel/antinonio#19]
https://sic.pt/Programas/terra-nossa/episodios/2019-10-06-Terra-Nossa-T3---Episodio-14-1

Nos videos da sic aparece a notificação do nonio

**Comment by PJFonseca** [comment]
Acabei de testar e não obtive nada do nonio. 

@brunomiguel consegues confirmar? 

Obrigado

**Comment by daniel3xxx** [comment]
Deixo aqui uns prints

https://ibb.co/dGhcZ1s
https://ibb.co/5WFYmp3

**Comment by brunomiguel** [comment]
Testei agora e não consigo replicar, @daniel3xxx @PJFonseca. Que Adblocker estás a usar? E já de agora, com outro adblocker (com a lista carregada) acontece o mesmo?

**Comment by brunomiguel** [comment]
Também não consigo replicar no telemóvel https://photos.app.goo.gl/f57mridXcTBy2eQU8

**Comment by daniel3xxx** [comment]
Onde me acontece que é no telemóvel, uso o adguard (modo VPN). No PC uso o ublock origin e de facto não consigo replicar. Será alguma incompatibilidade com o adguard para telemóvel? É estranho porque ás vezes ligo o adguard quando me aparece o nonio e assim que faço refresh á página já não volta a aparecer, mas neste site da sic isso não acontece.

**Comment by PJFonseca** [comment]
Posso então concluir que a nossa lista está boa e não precisa de mexer?

**Comment by daniel3xxx** [comment]
Sim. Deve ser alguma incompatibilidade com o adguard para telemóvel.

No entanto se também poderem testar, estou a usar o Adguard - Block Ads Without Root v3.2.150 com esta lista nos filtros personalizados.
