### ISSUE TITLE
melhoria do README

### ISSUE THREAD

**Issue by marado** [brunomiguel/antinonio#2]
De acordo com o que está em https://dd.indie.host/t/ajuda-lista-de-bloqueios-para-o-ublock-origin-dos-trackers-da-plataforma-nonio/807/1 (ou a minha interpretação), esta lista alimenta o nonio.pt, enquanto que o README diz que a lista vem da informação do nonio.pt. Se estou correcto e isto nasceu do que estava nonio.pt, entretanto foi alterado, e hoje em dia é esta informação que vai alimentar o site, então acho que isso devia estar melhor explicado no README.

**Comment by brunomiguel** [comment]
O README realmente não está correto, tendo em conta as alterações que foram feitas. Vou fazer a alteração durante esta tarde.

**Comment by brunomiguel** [comment]
Atualizei o README.
