### ISSUE TITLE
"Regras de bloqueio globais para os sites da rede nonio" list

### ISSUE THREAD

**Issue by rd-su** [brunomiguel/antinonio#20]
Hi,

the "Regras de bloqueio globais para os sites da rede nonio" list shouldn't to be used in uBlock Origin My Rules tab?

Regards

**Comment by brunomiguel** [comment]
Pode ser mais aí é só local. A intenção da presença delas na lista é qualquer utilizador poder ter acesso a elas sem ter que as configurar manualmente no adblocker.

**Comment by rd-su** [comment]
Estás a dizer que o uBlock vai interpretar na mesma aquela lista, e vai usá-la como se fossem regras de filtro dinâmicas, usadas no "My rules"?
Pelo teste que fiz, não as está a usar como regras de filtro dinâmicas.

Se não for assim, o utilizador terá de colocá-las manualmente, ou importar um ficheiro que as tenha, no "My rules".

**Comment by PJFonseca** [comment]
Malta,

Eu basicamente vou ao Tab Filters List, Campo Custom e clico no Import. Coloco o URL da lista aqui do anti-nonio, e fica a funcionar. 

Isto tudo no uBlock Origin :)

**Comment by brunomiguel** [comment]
> Estás a dizer que o uBlock vai interpretar na mesma aquela lista, e vai usá-la como se fossem regras de filtro dinâmicas, usadas no "My rules"?
> Pelo teste que fiz, não as está a usar como regras de filtro dinâmicas.
> 
> Se não for assim, o utilizador terá de colocá-las manualmente, ou importar um ficheiro que as tenha, no "My rules".

Tenho ideia de que ele as usava. Vou ter que testar quando tiver tempo (talvez amanhã ou sexta)

**Comment by rd-su** [comment]
> > Estás a dizer que o uBlock vai interpretar na mesma aquela lista, e vai usá-la como se fossem regras de filtro dinâmicas, usadas no "My rules"?
> > Pelo teste que fiz, não as está a usar como regras de filtro dinâmicas.
> > Se não for assim, o utilizador terá de colocá-las manualmente, ou importar um ficheiro que as tenha, no "My rules".
> 
> Tenho ideia de que ele as usava. Vou ter que testar quando tiver tempo (talvez amanhã ou sexta)

Se testares por exemplo, este link (https://www.zdnet.com/article/cycle-to-work-how-data-is-discovering-the-routes-you-didnt-know-you-needed/), podes ver que a regra "* 2mdn.net * block", que tens na lista, não está a ser aplicada.

**Comment by rd-su** [comment]
O mesmo também se aplica às regras "Bloqueio de scripts inline nos sites da rede nonio".

**Comment by Perksls** [comment]
@ruiumbelino essa regra é interpretada pelo uMatrix e não pelo ublock
Exemplo uMatrix https://github.com/gorhill/uMatrix/wiki/Examples-of-useful-rulesets


Se for só uBlock pelo meu uso recomendo esta lista junto com a EasyList

**Comment by rd-su** [comment]
> @ruiumbelino essa regra é interpretada pelo uMatrix e não pelo ublock
> Exemplo uMatrix https://github.com/gorhill/uMatrix/wiki/Examples-of-useful-rulesets
> 
> Se for só uBlock pelo meu uso recomendo esta lista junto com a EasyList

@Perksls , estas regras são interpretadas pelo uBlock, caso sejam inseridas/importadas no separador "My rules".

**Comment by Perksls** [comment]
> > @ruiumbelino essa regra é interpretada pelo uMatrix e não pelo ublock
> > Exemplo uMatrix https://github.com/gorhill/uMatrix/wiki/Examples-of-useful-rulesets
> > Se for só uBlock pelo meu uso recomendo esta lista junto com a EasyList
> 
> @Perksls , estas regras são interpretadas pelo uBlock, caso sejam inseridas/importadas no separador "My rules".

 Eu posso estar enganado, mas esta lista foi importada do anti-nonio que combina as duas, o uBlock para ad block e o uMatrix para controlar o que é carregado em termos de scripts, XHR, iframe etc

o funcionamento do Myrules é capaz de ter semelhanças com o uMatrix, não sei. 
De qualquer forma não vejo, como disse antes, porque não se deva usar o EasyList que tem uma lista brilhante se o objectivo é esse

**Comment by ruiumbelino** [comment]
Tens razão, pensava que te estavas a referir ao que foi dito no início deste issue.

As regras "Bloqueio de scripts inline nos sites da rede nonio" não são suportadas pelo uBlock.

**Comment by rd-su** [comment]
Eu uso a EasyList.

O que quero dizer, é que estas regras dinâmicas no uBlock, como as listas "Bloqueio de scripts inline nos sites da rede nonio" e "Regras de bloqueio globais para os sites da rede nonio", não podem ser usados no "Filter List", mas sim no "My rules".

Logo, quando um utilizador do uBlock importa o antinonio.txt no "Filter List", as regras dinâmicas não serão usadas, e julgo que era isso que vocês pretendem, pelo que podemos ver na página inicial.

É necessário terem uma lista para ser importada no "Filter List", e outra lista para ser importada no "My rules".

**Comment by Perksls** [comment]
eu sempre pensei que seriam para o uMatrix como disse, tanto que num issue anterior até foi referido isso.

Mas sim, em termos de Myrules, não me parece que dê para importar sequer a não ser dum file

**Comment by brunomiguel** [comment]
Sim, elas começaram por causa do uMatrix. A solução poderá passar por ter ficheiros separados para cada um destes adblockers (desculpem a demora mas a vida pessoal intrometeu-se e ela tem sempre prioridade)

**Comment by Perksls** [comment]
A questão é que a lista actualmente deverá funcionar com o uMatrix e UBlock. Faz sentido separar em duas versões e manter duas versões quando já funciona com as duas?

**Comment by rd-su** [comment]
Não vai haver adaptação para o uBlock?

> A questão é que a lista actualmente deverá funcionar com o uMatrix e UBlock. Faz sentido separar em duas versões e manter duas versões quando já funciona com as duas?

Julgava que já tínhamos chegado à conclusão de que a lista não funciona com o uBlock, na totalidade...

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1118 https://github.com/brunomiguel/antinonio/issues/24
