### ISSUE TITLE
Issue no site da TSF

### ISSUE THREAD

**Issue by rd-su** [brunomiguel/antinonio#21]
A regra "||nonio.globalmediagroup.pt^$important" está a bloquear o play do item em baixo, no site da TSF.

![2019-12-07_16h49_02](https://user-images.githubusercontent.com/10651797/70377895-c5175300-1911-11ea-8386-18fbc81747f7.png)

Exemplo: https://www.tsf.pt/portugal/sociedade/morreu-carlos-amaral-dias-pai-de-joana-amaral-dias-e-antigo-colaborador-da-tsf-11578399.html

**Comment by Perksls** [comment]
Penso que estava a bloquear mais coisas até, mas assim bloqueia a splash page. teste pfv

**Comment by rd-su** [comment]
Está a funcionar!

Obrigado
