### ISSUE TITLE
parou de funcionar no record.pt

### ISSUE THREAD

**Issue by sergiomb2** [brunomiguel/antinonio#23]
As  regras para o ublock na pagina https://nonio.pt/ublock.html já não funcionam ... 

Obrigado.

**Comment by PJFonseca** [comment]
Olá Sérgio,

A lista que referes foi a base para este repositório, mas neste momento, este repositório está bem diferente do apresentado no site nonio.pt.

Devo dizer que acedi ao record.pt e naveguei um pouco, consegui ver tudo sem que fosse chateado com os normais bloqueios.

Vou esperar pelo @brunomiguel ou pelo @Perksls para ver o que eles dizem, mas aparentemente, está tudo a funcionar correctamente com a nossa lista.

**Comment by Perksls** [comment]
yep confirmo, de minha parte continua tudo a funcionar sem qualquer problema.

**Comment by sergiomb2** [comment]
Olá ok , mas então na página  https://nonio.pt/ublock.html o link cá em baixo em vez de ser : abp:subscribe?location=https://nonio.pt/antinonio.txt&title=anti-nonio 
devia ser:
[abp:subscribe?location=https://raw.githubusercontent.com/brunomiguel/antinonio/master/antinonio.txt&title=anti-nonio](abp:subscribe?location=https://raw.githubusercontent.com/brunomiguel/antinonio/master/antinonio.txt&title=anti-nonio )

**Comment by PJFonseca** [comment]
Olá Sérgio,

Não é que o Tomahock ( @tomahock ) não o fizesse se pedíssemos, mas são coisas diferentes. Ele mantém aquela lista, nós (mais o @brunomiguel, eu  e o @Perksls só nos juntámos mais tarde ), criámos esta porque achámos que podia ser melhorada.

As duas são complementares mas não são a mesma. Dito isto, podes ter as duas no teu uBlock ;)

**Comment by sergiomb2** [comment]
ok obrigado

**Comment by tomahock** [comment]
Vou ver se me arranjo um tempinho para vir aqui buscar a lista e atualizar lá!
