### ISSUE TITLE
gravatar.com bloqueado

### ISSUE THREAD

**Issue by daniel3xxx** [brunomiguel/antinonio#25]
Após as ultimas actualizações, alguns site que usam o gravatar.com por ex.: https://review.lineageos.org/c/LineageOS/android_device_samsung_msm8974-common/+/279087/
Não aparece os avatares do users. Acontece o mesmo no pplware.com

**Comment by brunomiguel** [comment]
Resolvido. Podes forçar a atualização das regras no adblocker.
