### ISSUE TITLE
videos do cmjornal não carregam

### ISSUE THREAD

**Issue by daniel3xxx** [brunomiguel/antinonio#26]
Depois das ultimas actualizações os videos do cmjornal deixaram de carregar

Ex,: https://www.cmjornal.pt/portugal/detalhe/camara-de-videovigilancia-trama-dupla-que-assaltou-supermercado-em-gaia-veja-as-imagens?ref=HP_OutrasNoticias1

**Comment by brunomiguel** [comment]
Acabei de publicar uma alteração à lista. Podes testar, por favor?

**Comment by brunomiguel** [comment]
Resolvido, mas vou ter que ponderar esta alteração, já que me obrigou a retirar o bloqueio a um script do domínio deles, o www.cmjornal.pt/hits/scripts/cofinahits.js.

**Comment by daniel3xxx** [comment]
A funcionar agora. Obrigado

**Comment by daniel3xxx** [comment]
> Resolvido, mas vou ter que ponderar esta alteração, já que me obrigou a retirar o bloqueio a um script do domínio deles, o [www.cmjornal.pt/hits/scripts/cofinahits.js](http://www.cmjornal.pt/hits/scripts/cofinahits.js).

Update: após analisar o log no addon ublock origin, esse script do meu lado continua bloqueado pela lista EasyPrivacy e os vídeos reproduzem sem problema.
