### ISSUE TITLE
Record.pt - Image sliders (Fotogalerias) not working

### ISSUE THREAD

**Issue by alcpereira** [brunomiguel/antinonio#29]
I can't figure out why but I'm pretty sure uBlock's antinonio is breaking the slider script.
From what I've found jQuery, header.js and detalhe-multimedia.js are involved, but none of them are blocked.

The only way I found to resolve this was to remove the record.pt inline-script line from the list.

Any better way than doing that? Otherwise I'll request a pull to change this.

**Comment by brunomiguel** [comment]
I'll have to take a look at the website. I'll try doing it today, if my back pain allows me to.

**Comment by brunomiguel** [comment]
By the way, if possible, please leave an example link. Also, podes escrever em português à vontade :)

**Comment by brunomiguel** [comment]
A "culpa" é desta regra `||record.pt^$inline-script,important`, que está a bloquear o seguinte, que me parece que é a parte em javascript que faz a gestão do slider

`<script>
        $(function () {
            var configPubJson = {
                    slotNames: {
                        oopSlotName: 'OutOfPage',
                        mastheadSlotName: 'BTFhorz',
                        mrecSlotName: 'BTFvert',
                        leaderboardSlotName: 'BTFhorz',
                        inContentSlotName: 'BTFInContent'
[...]
</script>`

Vou comentar a regra indicada no primeiro parágrafo, para que o slider funcione, e aguardar pelo feedback da comunidade caso haja problemas com a alteração.

**Comment by brunomiguel** [comment]
**Se voltar a dar problemas, reabram este bug, por favor.**
Se não quiserem aguardar pela atualização automática do filtro no uBlock Origin, basta forçar a atualização dele nas opções do adblocker.

**Comment by brunomiguel** [comment]
Alteração testada com sucesso em:
- Firefox 80.0.1
- uBlock Origin 1.29.2

**Comment by alcpereira** [comment]
Alteração testada com sucesso em:
- Chrome 85.0.4183.83
- uBlock Origin 1.29.2
