### ISSUE TITLE
Update nonio.pt

### ISSUE THREAD

**Issue by alcpereira** [brunomiguel/antinonio#31]
Não sei se o site `nonio.pt` está diretamente ligado com esse github, mas a lista no site está desatualizada.

https://nonio.pt/antinonio.txt

O botão "Adicionar ao uBlock Origin" está com o link seguinte: "abp:subscribe?location=https://nonio.pt/antinonio.txt&title=anti-nonio" 

O link não funciona (não abre nem uBlock) e talvez seria melhor apontar para esse github (ou pelo menos uma versão release).

**Comment by brunomiguel** [comment]
Este repositório começou como um fork da lista do nonio.pt. Entretanto, a data altura, esta lista foi usada para o site. Se quiseres usar esta lista, tens as instruções no [README](https://github.com/brunomiguel/antinonio/blob/master/README.md). Mas, assim que possível, vou fazer um PR para a lista do site, para que seja atualizada.

**Comment by brunomiguel** [comment]
Submeti um PR ao repositório do Nonio.pt. Agora é aguardar para ver se é aprovado
