### ISSUE TITLE
Suporte adblock plus, Opera e Vivaldi

### ISSUE THREAD

**Issue by Perksls** [brunomiguel/antinonio#9]
Se for adicionado na primeira linha:
[Adblock Plus 2.0]

A lista deverá ser compatível com o Adblock Plus, com o blocker stock do Opera e Vivaldi mantendo compatibilidade com o uBlock

**Comment by brunomiguel** [comment]
E é compatível com o uMatrix?

**Comment by Perksls** [comment]
Sim, penso que sim. Eu não uso o uMatrix mas testei importar com esse header e não deu problema.

**Comment by Perksls** [comment]
testei agora e o comportamento com a primeira linha ou sem a linha no uMatrix é exactamente igual, pelo que funciona

**Comment by brunomiguel** [comment]
Atualizado. Desculpa a demora na resposta.
